# Travis CI
sudo: required
group: deprecated-2017-Q4
dist: trusty
language: generic
python:
  - "2.7"
services:
  - docker

env:
  matrix:
     - "TESTLANG=Go"
     - "TESTLANG=JavaScript"
     - "TESTLANG=PHP"
     - "TESTLANG=Python"
     - "TESTLANG=Ruby"


before_script:
  # Runs travis_diff, printing the output to the terminal, and searches for travis-diff-continue
  # to determine if the suite should be installed and the current $TESTDIR test should run.
  - export RUN_TESTS=`./toolset/travis/travis_diff.py | tee /dev/tty | grep -oP "travis-run-tests \K(.*)"`

  - if [ "$RUN_TESTS" ]; then docker pull matheusrv/ssgberk; fi

script:
  # run-ci.py runs the diffing to see if travis needs to test this generator. Ideally/eventually,
  # we'd like to try and do the diffing before travis_clean & setup.
  # This will run the tests exactly as you would in your own vm:
  - if [ "$RUN_TESTS" ]; then docker network create ssgberk > /dev/null 2>&1 && docker run --network=ssgberk -v /var/run/docker.sock:/var/run/docker.sock --mount type=bind,source=`pwd`,target=/StaticSiteGeneratorBenchmarks matheusrv/ssgberk --mode verify --test-dir $RUN_TESTS; else echo 'Skipping test verification.'; fi
